On.MARKET_DATA_SNAPSHOT:{[MSG]
  .log.Inf "MARKET_DATA_SNAPSHOT"
  };

On.MARKET_DATA_INCREMENT:{[MSG]
  .log.Inf "MARKET_DATA_INCREMENT"
  };

On.MARKET_DATA_REQUEST_REJECT:{[MSG]
  .log.Inf "MARKET_DATA_REQUEST_REJECT"
  };